fileVersion: 1
id: "493"
mappingDefinitions:
  SOURCE_DATA:
    database: RUHULAMINS_DEV
    schema: SOURCE_DATA
  TARGET_DB:
    database: RUHULAMINS_DEV
    schema: TARGET_DEV
name: New Environment
type: Environment
